<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>WinExe</OutputType><AssemblyName>Qemik</AssemblyName><ApplicationIcon>Assets/qemik.ico</ApplicationIcon><ApplicationManifest>app.manifest</ApplicationManifest></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Qemik.Core/Qemik.Core.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.2" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.2" />
  </ItemGroup>
  <ItemGroup><None Update="Assets/**" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" /></ItemGroup>
  <ItemGroup><AvaloniaResource Include="Assets/Fonts/**" /></ItemGroup>
  <ItemGroup><AvaloniaResource Include="Assets/qemik-artwork.png" /></ItemGroup>
</Project>
